apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
        - name: recipe-app
          image: greatnate27/recipe-application:latest
          ports:
            - containerPort: 80